### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by astronouth7303** [ppb/pursuedpybear#327]
Implement sound!

* [x] Play a sound effect (#326)
* [ ] Background music (#344)
* [ ] Cancel sounds on scene change (#345)
* [ ] Reacting when sounds finish (#346)

**Comment by astronouth7303** [comment]
How much of this do we want for the next release?

**Comment by pathunstrom** [comment]
Honestly, you've done enough to make it valuable.

We can add the other features as we see fit. Might want to break them up into smaller issues, though.

**Comment by astronouth7303** [comment]
Ok, with the specifics broken out into individual issues, closing this.
